### ISSUE TITLE
Use OpenTSDB Expressions

### ISSUE THREAD

**Issue by johann8384** [turn/splicer#1]
Now that OpenTSDB's 2.3 release is close to a reality, we should migrate our Functions code to the equivalent OpenTSDB Expressions.

**Comment by ace-han** [comment]
@johann8384 Is there any feature release plan on this? I found it 7 months later after this issue being open

**Comment by johann8384** [comment]
I don't believe anyone is using this project, the company I was working with went another route entirely.

**Comment by ace-han** [comment]
@johann8384 Could you kindly tell what another route is and how? Or give us a reference how to doing this `Distributed Queries` so that we can speed up those long running queries especially for month, quarter, annual report. 

Million thanks
