### ISSUE TITLE
Please add documentation on howto for setup

### ISSUE THREAD

**Issue by jsbali** [turn/splicer#4]
Hey I wanted to try to it. But didn't find any doc for it. Can you point me to the docs.

**Comment by wicknicks** [comment]
Hi @jsbali,

Thanks for your note. I'll add a README file.

**Comment by ace-han** [comment]
I was recommended to try this out by https://github.com/OpenTSDB/opentsdb/issues/810
 Please add doc about how to use it. I am suffering slow queries on large duration queries

**Comment by johann8384** [comment]
I'll work with Arjun today on this.

**Comment by wicknicks** [comment]
@ace-han: this is done now.
